### ISSUE TITLE
Add compatibility for Starfinder game system

### ISSUE THREAD

**Issue by Freelancerjw** [kakaroto/fvtt-module-polyglot#20]
Would love to be able to use this with the Starfinder game system! Thanks for the consideration!

**Comment by kakaroto** [comment]
I don't use or know the starfinder system so I can't add support for it (as I don't know how languages are implemented in that system and the data structure used by SFRPG). I would suggest you ask the SFRPG system developer to send a pull request with support for it to polyglot or to comment here on what needs to be added. 
It's pretty simple to add support for a new system for someone who knows it.

3 things are required : 
1 - How to find the list of languages supported by the system : 
https://github.com/kakaroto/fvtt-module-polyglot/blob/master/polyglot.js#L14
2 - What the default language should be : 
https://github.com/kakaroto/fvtt-module-polyglot/blob/master/polyglot.js#L43
3 -  How to find the list of languages that a specific actor understands
https://github.com/kakaroto/fvtt-module-polyglot/blob/master/polyglot.js#L125

**Comment by kakaroto** [comment]
This was just fixed with merging #27. Closing!
