### ISSUE TITLE
Include Chatbubble as a part of language scrambling

### ISSUE THREAD

**Issue by JacobMcAuley** [kakaroto/fvtt-module-polyglot#4]
As a GM, some users may wish to use FVTT's chatbubble during text conversation. Currently, chatbubbles are not affected by polygot. Perhaps a future implementation could include an option to use chatbubbles as well? 

Thanks!

**Comment by kakaroto** [comment]
Know, still waiting for chat bubbles hooks to be added so I can control them. For now I can't do anything about it. But you did remind me to check and realized there never was an issue on FVTT tracker to remind Atropos to add a hook for chat bubble rendering.

**Comment by JacobMcAuley** [comment]
Thanks for getting it to work! My players are excited!
