### ISSUE TITLE
Document in the README the out-of-character vs in-character situation

### ISSUE THREAD

**Issue by Woodchip50** [kakaroto/fvtt-module-polyglot#40]
Is there a way to speak in a language out of character, as in without having a token which speaks it selected? 

For example, if my players find a message scribbled on a wall in draconic, and i want to post a message so the players who can read draconic can understand it, i can't seem to find a way to easily do this if there isn't an NPC i can hijack on the map, and it's rarely worth it to make a journal entry for a quick message. 

If i could just choose the language from the drop down then type out the message and post it, that would be really useful. 
If possible, I don't just mean typing "/draconic message", because I am a forgetful moron and have ruined a couple of secret messages by forgetting to type /ic before writing the message, which instead posts the message OOC and in english/common rather than the language i have selected from the drop down.

Otherwise, thanks for this awesome module! It is such a cool idea and I love it!

**Comment by kakaroto** [comment]
Speaking "out of character" is reserved for actual out of character speech (i.e: from this world, in English or whatever language you speak), and in-world languages are for in-character speech.
Having polyglot active on both IC and OOC messages will make it even more problematic for when you want to speak in plain text and for other people who don't want that feature.

You don't have to hijack a token to speak in character though, what most people though is to create a single Actor called "Narrator" or "GM" and assign it to their GM player (in the "Player Configuration" dialog). You can then speak in-character as the GM by simply prefixing your message with the `/ic` command. If you forget it to type it, then... there's not much I can do for that!

I know there's a module that can let you use `/as` command, so you could do `/as Wall the message` without having to create an actor, but I just can't remember which module that was.
I hope that helps.

**Comment by BernhardPosselt** [comment]
Can this be added to the README? It looked like the module was broken because it only works if you select a token.

**Comment by kakaroto** [comment]
Considering the number of times I've had to answer that question... why have I not thought of adding it to the README 🤦‍♂️ Thanks!

P.s: With #56 being merged soon, and an option that GMs can use to allow speaking out of character, that should hopefully at least make it less of an issue.
