### ISSUE TITLE
Unable to edit journal entries when Polyglot is enabled.

### ISSUE THREAD

**Issue by liskajp** [kakaroto/fvtt-module-polyglot#41]
When Polyglot is enabled clicking the edit button in the top right of the text field in the journal causes all text to disappear and the edit UI does not appear at the top of the text field.

Text can be typed still, but no edits save.

Running on a Pi4B, narrowed down using Find the Culprit.

**Comment by kakaroto** [comment]
What version of Foundry and which system (and version of the system) and which version of polyglot ? 
Find the Culprit may have been able to identify the cause as being Polyglot but can you confirm that enabling the module breaks journal entries and disabling it fixes it ? Is it possibly an incompatibility with another module that also needs to be enabled (i.e: did you test this with nothing but polyglot enabled) ? 
It all looks good from my side both with 0.6.6 and 0.7.1

**Comment by liskajp** [comment]
Foundry is 0.6.6 running on a RasPi 4b 2GB, Polyglot 1.1.1 

I've run with only Polyglot active and the problem persists.

**Comment by kakaroto** [comment]
I can't reproduce it and you're the first one to mention this issue.
What browser are you using and did you try a different browser? Although that shouldn't really matter since you say it works without the module...

Can you press F12 to open the dev console in Foundry and see if there's any errors in the console when you try to edit a journal entry ? If there is, please screenshot the console.

**Comment by liskajp** [comment]
It occurs on both Firefox and Chrome and in both the OSE and 5e module.

An error occurs, pasting text

> theme.min.js:9 Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
>     at N.customFormats (theme.min.js:9)
>     at theme.min.js:9
>     at it (theme.min.js:9)
>     at N (theme.min.js:9)
>     at uO (theme.min.js:9)
>     at N.customFormats (theme.min.js:9)
>     at theme.min.js:9
>     at it (theme.min.js:9)
>     at N (theme.min.js:9)
>     at uO (theme.min.js:9)
> N.customFormats @ theme.min.js:9
> (anonymous) @ theme.min.js:9
> it @ theme.min.js:9
> N @ theme.min.js:9
> uO @ theme.min.js:9
> N.customFormats @ theme.min.js:9
> (anonymous) @ theme.min.js:9
> it @ theme.min.js:9
> N @ theme.min.js:9
> uO @ theme.min.js:9
> (anonymous) @ theme.min.js:9
> map @ theme.min.js:9
> aO @ theme.min.js:9
> (anonymous) @ theme.min.js:9
> FS.fire @ tinymce.min.js:9
> fire @ tinymce.min.js:9
> nS @ tinymce.min.js:9
> fS @ tinymce.min.js:9
> (anonymous) @ tinymce.min.js:9
> (anonymous) @ tinymce.min.js:9
> ir @ tinymce.min.js:9
> o @ tinymce.min.js:9
> Ca.loadScripts @ tinymce.min.js:9
> Ca.loadQueue @ tinymce.min.js:9
> (anonymous) @ tinymce.min.js:9
> e @ tinymce.min.js:9
> (anonymous) @ tinymce.min.js:9
> (anonymous) @ tinymce.min.js:9
> ir @ tinymce.min.js:9
> o @ tinymce.min.js:9
> Ca.loadScripts @ tinymce.min.js:9
> Ca.loadQueue @ tinymce.min.js:9
> (anonymous) @ tinymce.min.js:9
> vS @ tinymce.min.js:9
> (anonymous) @ tinymce.min.js:9
> xN.render @ tinymce.min.js:9
> n @ tinymce.min.js:9
> (anonymous) @ tinymce.min.js:9
> ir @ tinymce.min.js:9
> e @ tinymce.min.js:9
> vo.executeHandlers @ tinymce.min.js:9
> m @ tinymce.min.js:9
> go @ tinymce.min.js:9
> vo.bind @ tinymce.min.js:9
> U @ tinymce.min.js:9
> init @ tinymce.min.js:9
> create @ foundry.js:14103
> _createEditor @ foundry.js:4910
> sheet._createEditor @ polyglot.js:401
> button.onclick @ foundry.js:4897
> Show 20 more frames****

**Comment by kakaroto** [comment]
Thank you, that was helpful! I'm able to reproduce this here now, by modifying the languages that Polyglot finds. I'm not sure though how you could have the situation where the bug happens.
That shouldn't affect, but do you have any custom languages set in the Polyglot settings ?
In the dev console, can you type the following commands and screenshot the result (make sure you click on the little arrow to the result) :
```js
PolyGlot.languages
```
and then with both polyglot enabled and disabled : 
```js
CONFIG.DND5E.languages
```
Hopefully that helps me figure out what caused it. In the meantime, I can add a workaround so if it happens again, it won't affect the editor.

**Comment by liskajp** [comment]
Will do! 

PolyGlot.languages
![image](https://user-images.githubusercontent.com/35777302/92207992-dca74c00-ee4f-11ea-93a5-ff12265a3176.png)


CONFIG.DND5E.languages with
![image](https://user-images.githubusercontent.com/35777302/92208033-ef218580-ee4f-11ea-912a-bb7aec1d6ba1.png)

CONFIG.DND5E.languages without

![image](https://user-images.githubusercontent.com/35777302/92208088-10827180-ee50-11ea-8c0f-94b8075c2eb2.png)

Please let me know if this isn't right/you need something else. I'm new to helping debug this sort of thing!

**Comment by kakaroto** [comment]
Thanks... this is... I don't know what to think of this, lol. You've been very helpful though in figuring it out!

Since it doesn't work for DND5E, and I noticed you mentioned OSE earlier, I just checked with the OSE system and I'm now getting the problem. I don't know if OSE changed something recently to the system that caused it to act that way, but this is indeed quite weird.
Maybe @mesfoliesludiques knows why the languages is an Array instead of an Object, and whether it's a new change or it was a bug from the start.
Note that you said dnd5e also had the problem, can you confirm if that's true ? 
Anyway, I've made appropriate fixes to prevent this and made a new release (v1.1.2) which works now with OSE.
Thanks for reporting and in your patience in debugging this issue!

**Comment by liskajp** [comment]
I'll respond with a check on 5e in the morning. Happy to help!

**Comment by mesfoliesludiques** [comment]
Hi !
I am pushing an update to OSE that should solve the issue. Let me know.

**Comment by kakaroto** [comment]
Thanks for the quick reaction!
I've fixed it with this : https://github.com/kakaroto/fvtt-module-polyglot/commit/579a86691dc25ff72735e2b8f5e262a647a3aa2b
I'll wait for your release and see how I can make it compatible with both old and new version.

**Comment by mesfoliesludiques** [comment]
I had an issue, my translation logic was bad, you should not have to update anything !

**Comment by liskajp** [comment]
Tested with both updates applied and it's working correctly now for me in both OSE and 5e!
