### ISSUE TITLE
Chat message created with a macro is always in Common

### ISSUE THREAD

**Issue by jeromelavoie** [kakaroto/fvtt-module-polyglot#54]
Hello all,

I am triggering a macro from a MultiLevelTokens drawing area to speak as a token located elsewhere in the dungeon. When a player enters the drawing, it calls the below macro with the following arguments: 

args[0] = V7AHiqGDjtQGvGtE
args[1] = "The Spider Queen blesses House Auvryndar! The battle to break House Freth's hold on the passages below brings victory after victory. We have seized key positions formerly held by our enemy. The defeat of House Freth is inevitable. Praise Lolth!"
args[2] = Elvish
args[3] = 2

The args[0] token knows Elvish and I have tried to trigger the macro with a non-elvish speaking character and an elvish speaking character.  It always comes out the same in comon.

```
Here are my versions :
Foundry VTT v0.6.6
System: D&D 5E v0.98
Polyglot v1.3
Multileveltokens v1.3.4
```

```js
// Speak a message from a specific token
//From Kekilla#7036's bubble macro 
//arguments required => args[0] === token_id
////////////////////////args[1] === chatContent
////////////////////////args[2] === language
////////////////////////args[3] === time in seconds

setTimeout(function() {
    let t = canvas.tokens.get(args[0]);
    if(t.actor?.data.data.attributes.hp.value === 0) {
        console.log("Speaker Token has 0 HP");
    } else {
        //target token

        //set language?
        $(`#polyglot select option [value=${args[2]}]`).attr("selected","selected");

         ChatMessage.create(    
        { 
            speaker : { token : t, actor : t.actor, scene : canvas.scene },
            content : args[1],
            type : CONST.CHAT_MESSAGE_TYPES.IC,
        },{chatBubble : false});
        ui.notifications.notify(args[1]);

        if(region !== null) {
            region.data.hidden == false;
            region.update({flags: {"multilevel-tokens": {disabled: true}}});
        }
  }
}, (args[3]*1000));
```

**Comment by jeromelavoie** [comment]
Might be linked to issue #37

**Comment by kakaroto** [comment]
I think the issue is in the macro command : 
`       $(`#polyglot select option [value=${args[2]}]`).attr("selected","selected");`

It should probably be like this instead : 
`        $(`#polyglot select`).val(args[2]);`

Setting the option as selected wouldn't change the actual select's value I think. Do you actually see it change in the UI ? If not, try the above and see if it works.

Though you should use the language id not its translated string (so `elvish` instead of `Elvish`)

**Comment by jeromelavoie** [comment]
I have not had the bright idea of upgrading Foundry to 0.7.5... same behavior as before.

Sad to report that the changed line triggers an error in the console:

```
SyntaxError: private fields are not currently supported
    _doMacros http://192.168.1.*:30000/modules/multilevel-tokens/multilevel.js:856
    _onUpdateToken http://192.168.1.*:30000/modules/multilevel-tokens/multilevel.js:1579
    _call http://192.168.1.*:30000/scripts/foundry.js:2426
    callAll http://192.168.1.*:30000/scripts/foundry.js:2386
    callOriginalFunction http://192.168.1.*:30000/modules/**furnace**/Patches/Patches.js:57
    <anonymous> http://192.168.1.*:30000/modules/**furnace**/QoL/Debug.js:33
    _handleUpdateEmbeddedEntity http://192.168.1.*:30000/scripts/foundry.js:29647
    _handleUpdateEmbeddedEntity http://192.168.1.*:30000/scripts/foundry.js:33793
    updateEmbeddedEntity http://192.168.1.*:30000/scripts/foundry.js:29615
multilevel.js:859:21
    _doMacros http://192.168.1.*:30000/modules/multilevel-tokens/multilevel.js:859
    _onUpdateToken http://192.168.1.*:30000/modules/multilevel-tokens/multilevel.js:1579
    _call http://192.168.1.*:30000/scripts/foundry.js:2426
    callAll http://192.168.1.*:30000/scripts/foundry.js:2386
    callOriginalFunction http://192.168.1.*:30000/modules/**furnace**/Patches/Patches.js:57
    <anonyme> http://192.168.1.*:30000/modules/**furnace**/QoL/Debug.js:33
    _handleUpdateEmbeddedEntity http://192.168.1.*:30000/scripts/foundry.js:29647
    _handleUpdateEmbeddedEntity http://192.168.1.*:30000/scripts/foundry.js:33793
    updateEmbeddedEntity http://192.168.1.*:30000/scripts/foundry.js:29615
```

**Comment by kakaroto** [comment]
Those errors clearly say they're from multilevel tokens module, it has nothing to do with chat messages or polyglot. Try the macro on its own, without the timeout and all the other stuff around it and see if it works

**Comment by jeromelavoie** [comment]
Heya Kakaroto, triggering the macro without all the extra stuff still happens on the polyglot line.

With the following macro, I get an error about Private Fields not supported
```js
    let t = canvas.tokens.get(args[0]);
        //target token

        //set language?
        $(`#polyglot select).val(args[2]);

         ChatMessage.create(    
        { 
            speaker : { token : t, actor : t.actor, scene : canvas.scene },
            content : args[1],
            type : CONST.CHAT_MESSAGE_TYPES.IC,
        },{chatBubble : false});
```

With this script, there is no error, but the message is always in common (even passing elvish as a parameter)
```js
    let t = canvas.tokens.get(args[0]);
        //target token

        //set language?
        $(`#polyglot select option [value=${args[2]}]`).attr("selected","selected");

         ChatMessage.create(    
        { 
            speaker : { token : t, actor : t.actor, scene : canvas.scene },
            content : args[1],
            type : CONST.CHAT_MESSAGE_TYPES.IC,
        },{chatBubble : false});
```

**Comment by jeromelavoie** [comment]
I'm a moron... I never noticed that the code you suggested was missing a `

This now works fine:
```js
    let t = canvas.tokens.get(args[0]);
        //target token

        //set language?
        $(`#polyglot select`).val(args[2]);

         ChatMessage.create(    
        { 
            speaker : { token : t, actor : t.actor, scene : canvas.scene },
            content : args[1],
            type : CONST.CHAT_MESSAGE_TYPES.IC,
        },{chatBubble : false});
```

**Comment by drewg13** [comment]
I was working on this exact problem and your code got me most of the way there and advice from kakaroto on Discord finished the job.  Here's code that does the trick by switching control to a "speaking" token that has the target language enabled and then back to the player token afterwards:

`let speakactor = game.actors.entities.find(c => c.name === args[0]);
let speaktoken = canvas.tokens.placeables.find(p => p.name === args[0]);
let playertoken = token;

speaktoken.control();

$(`#polyglot select`).val(args[2]);

ChatMessage.create(    
  { 
   speaker : { token : speaktoken, actor : speakactor, scene : canvas.scene },
   content : args[1],
   type : CONST.CHAT_MESSAGE_TYPES.IC,
  },{chatBubble : false});

playertoken.control();`

**Comment by jeromelavoie** [comment]
Welp, you're awesome @drewg13 ... I should have though of that.

Thanks guys!
